# fly.toml app configuration file generated for quaigleapp on 2023-10-19T13:21:57+02:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "quaigleapp"
primary_region = "ams"
swap_size_mb = 512

[build]

[http_service]
  internal_port = 8501
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ["app"]
