repos:

# black formatter
- repo: https://github.com/psf/black-pre-commit-mirror
  rev: 23.9.1
  hooks:
    - id: black
      language_version: python3.10

# ruff linter
- repo: https://github.com/astral-sh/ruff-pre-commit
  rev: v0.3.4
  hooks:
    - id: ruff

# mypy static type checker
- repo: https://github.com/pre-commit/mirrors-mypy
  rev: v1.8.0
  hooks:
  - id: mypy
    name: mypy-frontend
    files: ^frontend/
    args: [--config-file=frontend/mypy.ini]
    additional_dependencies: [types-requests]
  - id: mypy
    name: mypy-backend
    files: ^backend/
    args: [--config-file=backend/mypy.ini]
    additional_dependencies: [types-requests]
    
