repos:

# black formatter
- repo: https://github.com/psf/black-pre-commit-mirror
  rev: 23.9.1
  hooks:
    - id: black
      language_version: python3.10

# ruff linter
- repo: https://github.com/astral-sh/ruff-pre-commit
  rev: v0.3.4
  hooks:
    - id: ruff