repos:
  # taken from: https://black.readthedocs.io/en/stable/integrations/source_version_control.html
  # Using this mirror lets us use mypyc-compiled black, which is about 2x faster
  - repo: https://github.com/psf/black-pre-commit-mirror
    rev: 23.9.1
    hooks:
      - id: black
        # It is recommended to specify the latest version of Python
        # supported by your project here, or alternatively use
        # pre-commit's default_language_version, see
        # https://pre-commit.com/#top_level-default_language_version
        language_version: python3.10
# taken from: https://pypi.org/project/ruff/
- repo: https://github.com/astral-sh/ruff-pre-commit
  rev: v0.0.291
  hooks:
    - id: ruff