version: "3"
services:
  fastapi_service:
    container_name: quagleapi
    env_file: .env
    build: backend/.
    environment:
      OPENAI_API_KEY: ${OPENAI_API_KEY}
    command: "uvicorn app.fastapi_app:app --host 0.0.0.0 --port 8000 --reload"
    ports:
      - "8000:8000"
    networks:
      #user defined network bridge for all containers
      - frontend
      - backend

  streamlit_service:
    container_name: quagleapp
    build: frontend/.
    command: "streamlit run --server.port 8501 --server.enableCORS false streamlit_app.py"
    ports:
      - "8501:8501"
    networks:
      - frontend

networks:
  frontend:
  backend: