# fly.toml app configuration file generated for quaigleapi on 2023-10-18T10:41:00+02:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "quaigleapi"
primary_region = "ams"
# swap_size_mb = 512  # has no effect

[build]


[http_service]
  internal_port = 8000
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ["app"]