[theme]
base="light"
primaryColor="black"
backgroundColor="white"
secondaryBackgroundColor="white"
textColor="black"
font="monospace"

[logger]
# level = "debug"
level = "info"

[server]
runOnSave = false