name: code quality checks
run-name: quality checks triggered by @${{ github.actor }}

on: 
  push:
    paths: 
      - "frontend/**"
   
jobs:
    filter_changes:
      runs-on: ubuntu-latest
      outputs:
        output1: ${{ steps.filter.outputs.frontend }}
      steps:
        - uses: actions/checkout@v3
        - uses: dorny/paths-filter@v2
          id: changes
          with:
            filters: |
              frontend:
              - 'frontend/**'
    
    lint_frontend:
        name: lint frontend
        needs: filter_changes
        if: needs.changes.outputs.frontend == true
        runs-on: ubuntu-latest
        defaults:
            run:
                working-directory: ./frontend
        steps:
            - name: Filter changes
              uses: dorny/paths-filter@v2
              id: changes
              with:
                filters: |
                  backend:
                    - 'backend/**'
                  frontend:
                    - 'frontend/**'
        
            - name: Checkout code
              uses: actions/checkout@v3

            - name: Echo job and branchname
              run: echo "Running ${{ github.job }} on ${{ github.ref }}"

            - name: set up python
              uses: actions/setup-python@v2
              with:
                python-version: '3.10'

            - name: install dependencies
              run: |
                python -m pip install --upgrade pip
                pip install -r requirements.txt

            - name: lint with black
              uses: psf/black@stable
            
            - name: lint with ruff
              uses: chartboost/ruff-action@v1